export const strings = {
  articlesInCarton: 'Articles In Carton',
  cancel: 'Cancel',
  confirm: 'Confirm',
  article: 'article',
  articles: 'Articles',
  articleNo: 'article no.',
  cartonNo: 'carton no.',
  cartons: 'Cartons',
  act: 'act',
  actWithDot: 'act.',
  pullTrigger: 'Pull the trigger to start reading.',
  summary: 'Summary',
  pullTriggerScanBarcode: 'Pull the trigger to scan a carton barcode.',
  addressLasVegas: '2601 - Las Vegas (tst)',
  prepare: 'Prepare',
  delete: 'Delete',
};
